### ISSUE TITLE
Push proxy API for official linphone clients

### ISSUE THREAD

**Issue by basncy** [BelledonneCommunications/flexisip-account-manager#1]
Can we provide a push proxy API to wake up the official linphone mobile client?
something like https://api.linphone.org/push/$type/$event?api-token=$api-token&device-token=$token
where the api-token can be added for abuse.

This could also be filled into external-push-uri= in flexisip.conf, or a webhook for other PBX, improving the user experience who don't want to customize the apn/api-key to apple/google push system and rebuild their own linphone mobile client corresponsively.

**Comment by edhelas** [comment]
At the moment the API only send push-notifications for the account registration flow as described there: https://subscribe.linphone.org/api#post-accountcreationtokenssend-by-push

We don't have any plans internally to support this new features. If you are interested by it please contact our Commercial team there https://www.linphone.org/contact
