### ISSUE TITLE
How to sync contact list with an account?

### ISSUE THREAD

**Issue by petervnv** [BelledonneCommunications/flexisip-account-manager#7]
Hi,

I am having a hard time understanding the purpose of contact lists as there doesn't seem to be much documentation on that function.
I was expecting that adding a contacts list to an account via FlexiAPI would result in those contacts in that list being imported into that account in whatever client (iOS or Android) is being used but that doesn't seem to be the case.
Am I misunderstanding the purpose of contacts lists? Is there any documentation I should be reading?

Thanks,
Peter

**Comment by Viish** [comment]
Hi @petervnv,

For those contacts to be synced in the app, there is a "friend list uri" that has to be set in the config of the app.
This URI is automatically set when you configure your account on the client by flashing the QR Code displayed in the account manager, but not if you simply connect using your credentials.
Currently there is no UI setting to fill that URI manually.

Cheers,

**Comment by petervnv** [comment]
Thanks for the quick explanation. Saved me hours of reading through the source code.

Cheers

**Comment by petervnv** [comment]
Hi again @Viish 

I was able to get it working by adding the contacts-vcard-list parameter to linphonerc, thanks.

But I still have the problem that I can't select any of the contacts to use in a LIME chat. I opened a new ticket about that [here](https://github.com/BelledonneCommunications/linphone-android/issues/2117).

Do you want me to generate new logs and only paste the messages part from Android studio since the logs I posted in that ticket are not easy to read because of the formatting?
