### ISSUE TITLE
proper formatting for linphonerc xml file for remote provisioning?

### ISSUE THREAD

**Issue by petervnv** [BelledonneCommunications/flexisip-account-manager#8]
Hi,

I followed the remote provisioning guide [here](https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Remote%20Provisioning/) but even when I use the provided linpone provisioning xml file I always get a 500 error when the client tries to download and apply the provisioning file.

In my .env I have:

```
# Account provisioning
ACCOUNT_PROVISIONING_RC_FILE=linphonerc.xml
ACCOUNT_PROVISIONING_OVERWRITE_ALL=true
ACCOUNT_PROVISIONING_USE_X_LINPHONE_PROVISIONING_HEADER=true
```

and the linphonerc.xml I placed in the flexiapi/public/ folder which is copy/paste from the example on your wiki page:

```
<config xmlns="http://www.linphone.org/xsds/lpconfig.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.linphone.org/xsds/lpconfig.xsd lpconfig.xsd">
<script/>
<section name="sip">
<entry name="default_proxy" overwrite="true">0</entry>
</section>
<section name="net">
<entry name="nat_policy_ref" overwrite="true">~OuCpkaPzCwyvMo</entry>
</section>
<section name="misc">
<entry name="transient_provisioning" overwrite="true">1</entry>
<!--  apply remote provisioning only once -->
</section>
<section name="nat_policy_default_values">
<entry name="stun_server">stun.linphone.org</entry>
<entry name="protocols">stun,ice</entry>
</section>
<section name="nat_policy_0">
<entry name="ref" overwrite="true">~OuCpkaPzCwyvMo</entry>
<entry name="stun_server" overwrite="true">stun.linphone.org</entry>
<entry name="protocols" overwrite="true">stun,ice</entry>
</section>
<section name="auth_info_0" overwrite="true">
<entry name="username" overwrite="true">bilbo.baggins</entry>
<entry name="ha1" overwrite="true">7f37aeccfad9855e4584c5465d6b4638</entry>
<entry name="realm" overwrite="true">sip.linphone.org</entry>
<entry name="domain" overwrite="true">sip.linphone.org</entry>
<entry name="algorithm" overwrite="true">MD5</entry>
</section>
<section name="proxy_0" overwrite="true">
<entry name="reg_proxy" overwrite="true"><sip:sip.linphone.org;transport=tls></entry>
<entry name="reg_route" overwrite="true"><sip:sip.linphone.org;transport=tls></entry>
<entry name="reg_identity" overwrite="true">"Bilbo Baggins" <sip:bilbo.baggins@sip.linphone.org></entry>
<entry name="realm" overwrite="true">sip.linphone.org</entry>
<entry name="quality_reporting_collector" overwrite="true">sip:voip-metrics@sip.linphone.org;transport=tls</entry>
<entry name="quality_reporting_enabled" overwrite="true">1</entry>
<entry name="quality_reporting_interval" overwrite="true">180</entry>
<entry name="reg_expires" overwrite="true">31536000</entry>
<entry name="reg_sendregister" overwrite="true">1</entry>
<entry name="publish" overwrite="true">1</entry>
<entry name="avpf" overwrite="true">1</entry>
<entry name="avpf_rr_interval" overwrite="true">1</entry>
<entry name="nat_policy_ref" overwrite="true">~OuCpkaPzCwyvMo</entry>
</section>
</config>
```

But it seems something is wrong with the file since I always get a 500 error and it complains about the syntax starting on line 1:

```
<!-- syntax error, unexpected '=' in linphonerc.xml on line 1
 (500 Internal Server Error) -->
```

I wonder if I am missing some needed library or configuration to make this work?

**Comment by petervnv** [comment]
Apparently your own FlexiAPI QRcode provisioning is also not working as I just tested it now.

![Screenshot from 2024-03-06 16-46-29](https://github.com/BelledonneCommunications/flexisip-account-manager/assets/6282595/2a968dda-e6bd-49df-a415-83b7954af780)

When trying to apply the config it throws an http error (screenshot below)

![qrcode_error](https://github.com/BelledonneCommunications/flexisip-account-manager/assets/6282595/a425fe4d-dfea-444e-bd68-b5a3fb98ae6f)

**Comment by edhelas** [comment]
@petervnv ACCOUNT_PROVISIONING_RC_FILE must be... a rcfile.

The XML example file you put in is what is actually generated by the provisioning code.
Also this file has nothing to do in the `flexiapi/public/` directory.

In ACCOUNT_PROVISIONING_RC_FILE you need to put something like the example of the "Linphonerc configuration file" part of the tutorial you followed.

**Comment by petervnv** [comment]
Thanks for getting back to me @edhelas 
To see if I undestood you correctly,  I am supposed to put in the ACCOUNT_PROVISIONING_RC_FILE section of the env file the actual text of the parameters directly instead of pointing to a file where they are stored?

Something like

ACCOUNT_PROVISIONING_RC_FILE= **"**
[net]
download_bw=2048
upload_bw=1024
firewall_policy=ice
stun_server=stun.linphone.org

[sip]
sip_tcp_port=5070
ping_with_options=0
media_encryption=none
dscp=0x0

[video_codec_0]
mime=VP8
rate=90000
enabled=1

[video_codec_1]
mime=H264
rate=90000
enabled=1
recv_fmtp=profile-level-id=428014

**"**  ( I am assuming I need to use quotes to open and close but please correct me if I'm wrong)

**Comment by petervnv** [comment]
Ah ok, and I shouldn't store it in public folder right?
Where should I store that rcfile then?

**Comment by edhelas** [comment]
Somewhere private where it can be accessed by PHP

**Comment by Viish** [comment]
@edhelas the RC file is valid (from SDK point of view), the `recv_fmtp=useinbandfec=1` is expected written like that.

**Comment by edhelas** [comment]
> @edhelas the RC file is valid (from SDK point of view), the `recv_fmtp=useinbandfec=1` is expected written like that.

Possible that the value need some quotes to be handled properly ?

    recv_fmtp="useinbandfec=1"

**Comment by petervnv** [comment]
Yup, using the quotes worked.
Thanks
