### ISSUE TITLE
Admin account cannot delete devices

### ISSUE THREAD

**Issue by petervnv** [BelledonneCommunications/flexisip-account-manager#9]
Hi,

Just updated to latest master (7418d79) and ran the migrations. I noticed that the admin account can no longer delete devices. Seems that it no longer likes the UUID and needs a different parameter now?:

For example:
https://my.instance.com/admin/accounts/27/devices/urn:uuid:f79b366f-60d3-0032-b1c7-603f754bc64f/delete

throws the error about a missing parameter: 

"Missing required parameter for [Route: admin.account.device.index] [URI: admin/accounts/{account}/devices] [Missing parameter: account]."

![Screenshot from 2024-04-10 17-48-20](https://github.com/BelledonneCommunications/flexisip-account-manager/assets/6282595/0a05cc36-c61d-4773-93c8-66a40ae17bf4)

P.S. I tested logging as a non admin user and he can still delete his own devices without issues. Only the admin account seems to no longer work as expected

**Comment by petervnv** [comment]
Hi again,

Just to let you know I just tested again on a clean install with a fresh database and the bug is confirmed.

I also noticed another bug when attempting to create an admin account using `php artisan accounts:create-admin-account `

Although the account is created sucessfully (I checked in the database) it throws an error complaining about the undefined variable $apiKey (screenshot attached)

![Screenshot from 2024-04-22 18-08-40](https://github.com/BelledonneCommunications/flexisip-account-manager/assets/6282595/2413f8a5-f9e1-405a-9338-12b7b3a5f4ea)

**Comment by edhelas** [comment]
Fixed in https://gitlab.linphone.org/BC/public/flexisip-account-manager/-/commit/3a9e62394cdc64dce6a86667cc22c9123426576a
